### ISSUE TITLE
Problem in write_netlist()

### ISSUE THREAD

**Issue by TristanLbrn** [pyphs/pyphs#13]
Problem occurs while running 'RLC' test. The 'add_path()' function works, then the script stops in 'write_netlist'. 
The folder  'graphs' in pyphs might be not correctly added to pyphs package.

**OS** : Windows 10
**VERSION** : 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]

runfile('C:/Users/trist/Documents/GitHub/pyphs/tests/RLC.py', wdir='C:/Users/trist/Documents/GitHub/pyphs/tests')
Reloaded modules: paths, pyphs, symbolics
Traceback (most recent call last):

  File "<ipython-input-44-7a406eecf8cb>", line 1, in <module>
    runfile('C:/Users/trist/Documents/GitHub/pyphs/tests/RLC.py', wdir='C:/Users/trist/Documents/GitHub/pyphs/tests')

  File "C:\Users\trist\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Users\trist\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

  File "C:/Users/trist/Documents/GitHub/pyphs/tests/RLC.py", line 124, in <module>
    write_netlist()

  File "C:/Users/trist/Documents/GitHub/pyphs/tests/RLC.py", line 47, in write_netlist
    from pyphs.graphs.netlists import Netlist

ImportError: No module named 'pyphs.graphs'; 'pyphs' is not a package

**Comment by afalaize** [comment]
A lot of improvements where made since this issue was opened, so that it shall be closed now. @TristanLbrn Do you confirm?

**Comment by TristanLbrn** [comment]
Yes, the paths have been corrected. I close this issue.
