### ISSUE TITLE
Moving to sympy 1.1 introduce errors

### ISSUE THREAD

**Issue by afalaize** [pyphs/pyphs#49]
[Appveyor build 1.0.188](https://ci.appveyor.com/project/afalaize/pyphs/build/1.0.188) passes with sympy v1.0, but same code with sympy v1.1 [build 1.0.192](https://ci.appveyor.com/project/afalaize/pyphs/build/1.0.192) does not pass.
Windows user are invited to stick on sympy v1.0 (see [build 1.0.194](https://ci.appveyor.com/project/afalaize/pyphs/build/1.0.194)).

**Comment by afalaize** [comment]
The previous  comment is wrong.
In fact, due to [this issue](https://github.com/sympy/sympy/issues/12938), the release sympy 1.1 can not be used at all with pyphs (no matter the platform). So it is better to stick to the release sympy 1.0 untill [this PR](https://github.com/sympy/sympy/pull/12957) is merged.

**Comment by asmeurer** [comment]
Hi, we will be coming out with a release candidate for 1.1.1 soon. I would appreciate it if you could test it before 1.1.1 final so that we can avoid further regressions.

**Comment by afalaize** [comment]
Hi;

I updated my comment. Tests seems ok for hstcak and vstack, but we still have an issue, at least on MacOsx:
```
======================================================================
ERROR: Failure: ShapeError ()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/afalaize/Developement/anaconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/afalaize/Developement/anaconda3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/afalaize/Developement/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/afalaize/Developement/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/afalaize/Developement/anaconda3/lib/python3.6/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Users/afalaize/Developement/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/afalaize/Developement/repos/pyphs/pyphs/tests/test_cases.py", line 16, in <module>
    from .SimulationTest import (simulation_rlc_with_split,
  File "/Users/afalaize/Developement/repos/pyphs/pyphs/tests/SimulationTest.py", line 17, in <module>
    from pyphs.tutorials.core import core as nlcore
  File "/Users/afalaize/Developement/repos/pyphs/pyphs/tutorials/core.py", line 83, in <module>
    core.reduce_z()
  File "/Users/afalaize/Developement/repos/pyphs/pyphs/core/structure/R.py", line 83, in reduce_z
    Mnl = types.matrix_types[0].vstack(*mat)
  File "/Users/afalaize/Developement/anaconda3/lib/python3.6/site-packages/sympy/matrices/common.py", line 604, in vstack
    return reduce(kls.col_join, args)
  File "/Users/afalaize/Developement/anaconda3/lib/python3.6/site-packages/sympy/matrices/sparse.py", line 992, in col_join
    raise ShapeError()
sympy.matrices.common.ShapeError

----------------------------------------------------------------------

```
I will try to find a simpler case.

**Comment by afalaize** [comment]
It seems the problem is solved for Matrix but not for SparseMatrix

**Comment by certik** [comment]
@afalaize would you mind creating a minimal example for the SparseMatrix problem? Let's fix it.

**Comment by asmeurer** [comment]
Sparse matrix stacking was fixed for the 1.1.1 release https://github.com/sympy/sympy/pull/13031

**Comment by certik** [comment]
Ah cool. @afalaize, please let us know if it is fixed now.

**Comment by afalaize** [comment]
Travis and AppVeyor tests pass. Thank you for tracking the issue!

Sympy 1.1.1 is now required for installing pyphs.
